ryan4yin/nixos-and-flakes-book

docs/nixos-with-flakes/nixos-with-flakes-enabled.md, docs/zh/nixos-with-flakes/nixos-with-flakes-enabled.md
Very minor fix here: `hx` starts Helix rather than `helix` on NixOS https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/editors/helix/default.nix#L49 and via the flake
(Some distros do rename the binary to `helix` like [the Arch package](https://archlinux.org/packages/extra/x86_64/helix/) because of a conflict with another `hx` binary.)
Thanks!
=> fix: use 'hx' to start the Helix editor

docs/introduction/index.md
Minor typo in `docs/introduction/index.md`, first paragraph, to add a space between "**files**" and "**(**".
=> fix: typo [add space between word and open parenthesis]

docs/nixos-with-flakes/modularize-the-configuration.md
Great documentation!
- I did not understand exactly at the begining how Nix passes arguments in the `imports` list. I made a small example section which describes the observed behavior.
I hope its correct. I think it greatly helps to understand how these things are called. Maybe there is a reference to this?
Do you know?
=> feat: Add explanation how arguments are passed to imports in `imports`

docs/nixos-with-flakes/modularize-the-configuration.md
I'm new to Nix, but I'm _pretty_ sure there needs to be a semicolon after each key-value declaration in an attribute set, even when using `inherit`.
The same error doesn't seem to appear in the Chinese translation for this page (the two versions seem to have diverged a bit).
=> Fix syxtax error in Modularize the Configuration

flake.lock, flake.nix
I wanted to contribute to this repo and stumbled upon that Nix rebuilds chromium (because of `nixpkgs/release-23.11` and overlay), when you invoke `nix develop`.
This PR effectively prevents building chromium from source and instead will pull binary from cache.
=> fix: chromium rebuild

docs/nixos-with-flakes/start-using-home-manager.md
- Changed the "Home Manager Manual"  url link on the "Getting Started with Home Manager" section from `*.html` to `*.xhtml`
=> fix: "Home Manager Manual" refrence changed from `.html` to `.xhtml`

docs/zh/the-nix-language/index.md
```nix
''the value of a is:
''${a}
''
```
转义后输出应当为：`the value of a is: ${a}` 而不带有转义所用的 `''`.
=> fix: '' escape example comment

docs/nixos-with-flakes/add-custom-cache-servers.md, docs/zh/nixos-with-flakes/add-custom-cache-servers.md
Fixes 44 misspellings of the word `substituters` across two files:
- docs/nixos-with-flakes/add-custom-cache-servers.md
- docs/zh/nixos-with-flakes/add-custom-cache-servers.md
=> Fixes typo: substituers -> substituters

docs/nixos-with-flakes/introduction-to-flakes.md
=> fix: typo in introduction-to-flakes

docs/other-usage-of-flakes/inputs.md
The regular git flake input doesn't support LFS yet, so a tar.gz link is needed here.
=> add: a way to input your flake through a tar.gz link

docs/nixpkgs/callpackage.md, docs/nixpkgs/overriding.md, docs/zh/nixpkgs/callpackage.md, docs/zh/nixpkgs/overriding.md
This PR fixes some typos.
Furthermore, the PR future-proofs the code examples by adding `--file` parameter to `nix repl` when importing `nixpkgs`. Nix already produces a warning that future versions will require using '--file' parameter to import files. This PR prepares the book for when the '--file' parameter is mandatory.
=> Improve code examples

docs/nixos-with-flakes/other-useful-tips.md
When executing I received errors `rg: command not found`
=> Add missing ripgrep to nix shell

docs/best-practices/remote-deployment.md, docs/zh/best-practices/remote-deployment.md
=> feat:  remote-deployment - about ssh known_hosts

README.md, docs/development/distributed-building.md, docs/development/intro.md, docs/development/kernel-development.md, docs/development/packaging-101.md, docs/nix-store/add-binary-cache-servers.md, docs/nix-store/host-your-own-binary-cache-server.md, docs/nixos-with-flakes/get-started-with-nixos.md, docs/nixos-with-flakes/introduction-to-flakes.md, docs/nixos-with-flakes/modularize-the-configuration.md, docs/nixpkgs/multiple-nixpkgs.md, docs/other-usage-of-flakes/module-system.md, docs/other-usage-of-flakes/testing.md, docs/zh/development/distributed-building.md, docs/zh/development/intro.md, docs/zh/development/kernel-development.md, docs/zh/development/packaging-101.md, docs/zh/nix-store/add-binary-cache-servers.md, docs/zh/nix-store/host-your-own-binary-cache-server.md, docs/zh/nixos-with-flakes/get-started-with-nixos.md, docs/zh/nixos-with-flakes/introduction-to-flakes.md, docs/zh/nixpkgs/multiple-nixpkgs.md, docs/zh/other-usage-of-flakes/module-system.md, docs/zh/other-usage-of-flakes/testing.md
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
=> link to new nixos wiki

docs/.vitepress/config.ts
The configuration on the sidebar for the section _Nix Store & Binary Cache_ on page _Add Binary Cache Servers_ missed a '/' in the link, to reference the root of the document.
That error resulted only in the button **Next page** that referenced the _Preface_ page.
=> Fixed an error with the next and prev navigation

docs/best-practices/remote-deployment.md
Hi, thanks for the tutorial. Was confused by this. If I'm not missing something, this is a typo.
=> Fix typo in remote-deployment.md: .#nixos-text -> .#my-nixos

docs/en/nixos-with-flakes/other-useful-tips.md
trailing slash caused to copy directory. so the output was 
```shell
/etc/nixos/nixos-config/*.nix
```
and should be
```shell
/etc/nixos/*.nix
```
=> docs: fix logic typo

docs/en/development/intro.md
The changes tweak the example flakes so they will output the correct `nodejs` version
In my case, `pkgs.nodejs` points to `node v20.19.0` and that's what the `shellHook` outputs. Thought, in a dev shell, `nodejs` is set to version 18
The fix is somewhat awkward, I guess there's a more lean way to use the same package version in both places, but I'm not sure the example merits it
=> Update intro.md to echo the right nodejs version

docs/en/best-practices/nix-path-and-flake-registry.md, docs/en/nixos-with-flakes/introduction-to-flakes.md
- NixOS automatically manages the flake registry because I fixed it.
- Clarify that nix-channel does have a spiritual successor in flakes in the form of the registry, but that it's kind of useless.
=> Update flake registry related pages

docs/en/other-usage-of-flakes/inputs.md
The link to "Flakes Inputs - Nix Manual" in [this page](https://nixos-and-flakes.thiscute.world/other-usage-of-flakes/inputs) would actually point to [the section explaining Flake References](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#flake-references). I changed the link to point to the [expected section](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#flake-inputs).
The correction of the typo "Offical" to "Official" was done automatically by the `typos -w` command as instructed in the [contributing guidelines](https://github.com/ryan4yin/nixos-and-flakes-book/blob/bedbe5298feecd9a4d475da3b6edec505ab358aa/.github/CONTRIBUTING.md).
=> Fix link in other-usage-of-flakes/inputs

docs/en/best-practices/run-downloaded-binaries-on-nixos.md, docs/zh/best-practices/run-downloaded-binaries-on-nixos.md
'buildFHSUserEnv' has been renamed to 'buildFHSEnv' and was removed in 25.11
=> fix:update 'buildFHSUserEnv' to 'buildFHSUserEnv'

docs/en/development/intro.md
code examples and docs had different Node versions
so I fixed it as it is a little bit confusing
If I missed or misunderstood anything and this is actually correct, I apologize deeply.
Please correct me if I am wrong. 🙏 
Here are the two changed sections:
- Look at almost the end of https://nixos-and-flakes-book-git-fork-truebe-f1314b-ryan4yins-projects.vercel.app/development/intro#creating-a-development-environment
- At the start of this section after the code block: https://nixos-and-flakes-book-git-fork-truebe-f1314b-ryan4yins-projects.vercel.app/development/intro#creating-a-development-environment-with-pkgs-runcommand
=> docs: unify Node version
