- docs/.vitepress/config.ts
> Update config.ts to correct spelling "Pracetice" to "Practice"

- docs/nixos-with-flakes/other-useful-tips.md
> chore: typo

- docs/introduction/advantages-and-disadvantages.md
Just noticed a couple grammar issues / typos
> Fix grammar/typos advantages-and-disadvantages.md

- docs/.vitepress/config.ts
> Correct typo

- docs/nixos-with-flakes/start-using-home-manager.md
I'm a complete nix/nix-os newbie here, and while following your amazing guide, I had trouble making the `home.nix` configuration pass the build.
Luckily I've followed your nix language read suggestions and was able to fix it myself :star_struck: 
Thanks a lot for this amazing guide!
> fix: home.nix content example

- docs/introduction/advantages-and-disadvantages.md
This is the preferred capitalization for the npm brand name
https://css-tricks.com/start-sentence-npm/
> introduction/advantages-and-disadvantages.md: NPM -> npm

- docs/.vitepress/config.ts
It should be distributed building not distribution building.
> Fixed minor typo

- docs/nixos-with-flakes/start-using-home-manager.md
- docs/zh/nixos-with-flakes/start-using-home-manager.md
issue https://github.com/ryan4yin/nixos-and-flakes-book/issues/68
> fix: 'exa' removed due to unmaintained upstream.

- docs/nixos-with-flakes/add-custom-cache-servers.md
This is a pretty small change that improves wording.  
By the way, using this occasion to thank you for making such a great guide, i wish i found it sooner!
> fix: improve wording

- docs/nixos-with-flakes/introduction-to-flakes.md
* Fix uppercase on title
* Fix typo on word
> fix: typo in introduction-to-flakes

- README.md
Former link was of a mobile version page.
Change it to the desktop version would be better.
> Changed the link.

- docs/nixos-with-flakes/nixos-with-flakes-enabled.md
- docs/zh/nixos-with-flakes/nixos-with-flakes-enabled.md
> feat: lazy evaluation

- docs/best-practices/remote-deployment.md
- docs/development/cross-platform-compilation.md
- docs/development/intro.md
- docs/faq/index.md
- docs/nixos-with-flakes/downgrade-or-upgrade-packages.md
- docs/nixos-with-flakes/start-using-home-manager.md
- docs/nixpkgs/overlays.md
- docs/zh/best-practices/remote-deployment.md
- docs/zh/development/cross-platform-compilation.md
- docs/zh/faq/index.md
- docs/zh/nixos-with-flakes/introduction-to-flakes.md
- docs/zh/nixos-with-flakes/nixos-with-flakes-enabled.md
- docs/zh/nixos-with-flakes/other-useful-tips.md
- docs/zh/nixos-with-flakes/start-using-home-manager.md
- docs/zh/nixpkgs/callpackage.md
Fix typos automatically via <https://github.com/crate-ci/typos>
> fix: fix typos

- docs/development/packaging-101.md
> fix(development/packaging-101.md): correct a typo

- docs/introduction/index.md
A "slippery experience" is not a common phrase, and brings to mind something challenging, hard to grasp, or likely to lose control of at any moment. A "smooth experience" is a common phrase, meaning no rough edges, encountering no snags or friction or unexpected pitfalls.
> introduction/index.md: fix word choice for clarity

- docs/.vitepress/config.ts
Remove "Adding Custom Cache Servers" as its file was moved to "Nix Store & Binary Cache" section when it was created.
> Remove "Adding Custom Cache Servers"

- docs/other-usage-of-flakes/module-system.md
- docs/zh/other-usage-of-flakes/module-system.md
> [Little Change]: 重写了模块系统关于省略 `config` key 的说明

- docs/zh/nixos-with-flakes/start-using-home-manager.md
> Fix typo `Homa` -> `Home` in chapter start-using-home-manager

- docs/.vitepress/config.ts
- package.json
- pnpm-lock.yaml
Fix https://github.com/markdown-it/markdown-it-cjk-breaks/pull/5
> feat: update depends, fix markdown-it-cjk-breaks

- docs/preface.md
Thank you for the book.
This PR is a minor change and seems warranted as remedying an actual language mistake.
> Small English grammar correction

- docs/other-usage-of-flakes/inputs.md
As the title suggests, followed by my personal usage: https://github.com/piyoki/nixos-config/blob/master/flake.nix#L134
> docs(other-usage-of-flakes/inputs): add tag and submodules input usage

- docs/nixos-with-flakes/nixos-flake-and-module-system.md
- docs/zh/nixos-with-flakes/nixos-flake-and-module-system.md
> fix: specialArgs & _module.args

- docs/en/best-practices/remote-deployment.md
- docs/en/development/cross-platform-compilation.md
- docs/en/development/intro.md
- docs/en/development/kernel-development.md
- docs/en/development/packaging-101.md
- docs/en/nix-store/add-binary-cache-servers.md
- docs/en/nixos-with-flakes/downgrade-or-upgrade-packages.md
- docs/en/nixos-with-flakes/modularize-the-configuration.md
- docs/en/nixos-with-flakes/nixos-flake-and-module-system.md
- docs/en/nixos-with-flakes/nixos-flake-configuration-explained.md
- docs/en/nixos-with-flakes/nixos-with-flakes-enabled.md
- docs/en/nixos-with-flakes/start-using-home-manager.md
- docs/en/other-usage-of-flakes/module-system.md
- docs/zh/best-practices/remote-deployment.md
- docs/zh/development/cross-platform-compilation.md
- docs/zh/development/intro.md
- docs/zh/development/kernel-development.md
- docs/zh/development/packaging-101.md
- docs/zh/nix-store/add-binary-cache-servers.md
- docs/zh/nixos-with-flakes/downgrade-or-upgrade-packages.md
- docs/zh/nixos-with-flakes/modularize-the-configuration.md
- docs/zh/nixos-with-flakes/nixos-flake-and-module-system.md
- docs/zh/nixos-with-flakes/nixos-flake-configuration-explained.md
- docs/zh/nixos-with-flakes/nixos-with-flakes-enabled.md
- docs/zh/nixos-with-flakes/start-using-home-manager.md
- docs/zh/other-usage-of-flakes/module-system.md
- flake.lock
- flake.nix
- package.json
- pnpm-lock.yaml
> feat: upgrade to nixos-25.05

- docs/en/index.md
- docs/zh/index.md
> Home page style improvements
